apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-6zpb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-6zpb
    app.kubernetes.io/part-of: test
  name: devfile-sample-code-with-quarkus-6zpb
  namespace: sdouglas1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-6zpb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-6zpb
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:3801b251329eb66b1b7f6937b06afa89ac2d8ad364afed7b0b720302c5f7de97
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
