apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jixp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jixp
    app.kubernetes.io/part-of: test
  name: hacbs-test-project-jixp
  namespace: sdouglas1-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hacbs-test-project-jixp
status:
  loadBalancer: {}
